- ModerationAPI/Against.md
- ModerationAPI/Players.md
- ModerationAPI/SendModerations.md
- README.md
- RemoteConfig.md
- _sidebar.md
Added Some Moderation Stuff and changed logo from http to https, because why not 💯
> Moderation API!

- UserAPI/AcceptIgnoreFriend.md
- UserAPI/GetByID.md
Added return response to AcceptIgnoreFriend
Changed description on return response for world information as this is only displayed for friends.
> Update Files after API update

- FavoritesAPI/AddFavorite.md
- FavoritesAPI/DeleteFavorite.md
- FavoritesAPI/ListFavorites.md
- _sidebar.md
New beta out that adds favorite friends and some other updates.
New tags also added, but not yet been activated internaly (was by accident but removed)
> Beta 2018.2.1

- UserAPI/Tags.md
> Added new tags

- ModerationAPI/SendPlayerModerations.md
- UserAPI/FriendStatus.md
- _sidebar.md
Sorry for all the pullrequests.
> Fix formatting, again.

- NotificationAPI/SendNotification.md
- README.md
marked notificationtype friendrequest as dead and pointed to https://vrchat.com/api/1/user/id/friendRequest
> marked endpoint user/[ID]/notification?type=friendRequest as dead

- AvatarAPI/GetByID.md
Tweaked
- unityPackageUpdated
- unityPackageUrl
- created_at
Added
- unityPackageUrlObject
- assetUrlObject
> Add/Edit Avatar GetByID endpoint return fields

- Objects/Avatar.md
- Objects/Notification.md
- Objects/User.md
- Objects/World.md
- Objects/unityPackage.md
- UserAPI/Delete.md
- UserAPI/Register.md
- Fixed register endpoint fields (Closes #28)
- Add UserAPI Delete endpoint
- Some other things I messed up
> Add endpoint, and fixes

- Archive/Against.md
- _sidebar.md
> Move Moderated Endpoint to Archive

- index.html
also it appears this doesn't work on properly; will need to look into it.
the loop is only called on initial page load; not when its redirected or already loaded.
so these results return 404 sometimes. @Foorack
> fix: clean redirects

- index.html
Currently the sidebar "jumps around" a lot, making it very hard to navigate. This fixes this bug.
> Minor fix to sidebar

- Archive/ModerationAPI/Against.md
- Archive/UserAPI/ListActive.md
- GettingStarted/QuickStart.md
- _sidebar.md
This endpoint is now admin-only.
> Moved "Search/List Active Users" to Archive

- tutorials/tags.markdown
Fusl (usr_ef614fba-dc73-40d6-8877-237d6efb82dd)
New tags:
"Never gonna give you up",
"system_not_cute",
"'; DROP DATABASE tags; -- ",
"'; DROP TABLE tags; -- "
> Add meaningless tags used by Fusl

- content/tutorials/tags.markdown
> Add missing Nyx tag

- content/tutorials/tags.markdown
> Define `show_mod_tags` tag

- content/tutorials/tags.markdown
> Add another meaningless tag

- README.md
Blocked by openopensource/openopensource.github.io#23
> Switch to github.io domain for openopensource.org

- layouts/partials/header.html
> Add link to metrics

- content/sdk/python.markdown
[Effects this page](https://vrchatapi.github.io/sdk/)
> Make python sdk getting started the same as SDK repo

- content/tutorials/tags.markdown
> Add admin_hide_member_count Group tag

- content/tutorials/tags.markdown
Added new meaningless tag with @Fusl
> Added "if you're reading this-" tag by Fusl

- content/sdk/python.markdown
Library structure changed
Fixes #131
> Issue #131
